// Caddy v2 configuration writer + reloader.
//
// The Caddy compose service mounts `${STORAGE_ROOT}/caddy` as a *directory*
// (not a file) at /etc/caddy so an atomic rename of Caddyfile re-resolves the
// inode without a container restart. Caddy is reloaded via its admin API on
// http://caddy:2019/load (no SIGHUP).
//
// Layout when the tunnel is enabled:
//   • Caddy listens on :443 with `tls internal` (self-signed root).
//   • Single site block for the FQDN — reverse-proxies to the api service
//     for /api/* and to the web (Vite/dist) for everything else.
//   • cloudflared talks to caddy:443 with `noTLSVerify` + SNI = hostname.
//
// When the tunnel is disabled, no Caddyfile is needed; Caddy is essentially
// idle inside the docker network. Operator can still hit api:4000 directly.

import { mkdirSync, writeFileSync, renameSync, existsSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { config } from '../config.js';
import { logger } from '../logger.js';

const CADDY_DIR = join(config.STORAGE_ROOT, 'caddy');
const CADDYFILE = join(CADDY_DIR, 'Caddyfile');
const CADDY_ADMIN = process.env.CADDY_ADMIN_URL ?? 'http://caddy:2019';

export interface CaddyfileParams {
  fqdn: string;        // e.g. "darrow.example.com"
  apiHost: string;     // e.g. "api"
  apiPort: number;     // e.g. 4000
  webHost: string;     // static site host (Vite preview or web container)
  webPort: number;
}

function render(p: CaddyfileParams): string {
  // ─────────────────────────────────────────────────────────────────────────
  // Single hostname, single Caddy site. /api/* goes to the express api;
  // everything else to the static web service. `tls internal` issues a
  // self-signed cert from Caddy's own CA; cloudflared trusts it because we
  // set noTLSVerify in the tunnel ingress config.
  // ─────────────────────────────────────────────────────────────────────────
  return `# Auto-generated by darrow-time-invoicing — DO NOT EDIT by hand.
# Source: apps/api/src/services/caddy.ts

{
\tadmin 0.0.0.0:2019
\tauto_https disable_redirects
}

${p.fqdn} {
\ttls internal
\thandle /api/* {
\t\treverse_proxy ${p.apiHost}:${p.apiPort}
\t}
\thandle {
\t\treverse_proxy ${p.webHost}:${p.webPort}
\t}
\tlog {
\t\toutput stdout
\t\tformat console
\t}
}
`;
}

/** Atomic-write the Caddyfile. Caddy's directory mount re-resolves the inode
 *  on every open(), so rename-into-place is safe and survives container
 *  restarts. */
export function writeCaddyfile(p: CaddyfileParams): string {
  mkdirSync(CADDY_DIR, { recursive: true, mode: 0o700 });
  const body = render(p);
  // Temp file lives in CADDY_DIR (not os.tmpdir) — /tmp and /storage are
  // separate filesystems inside the container, so a cross-fs rename trips
  // EXDEV. Same dir keeps the rename atomic.
  const tmp = join(CADDY_DIR, `.Caddyfile.${randomBytes(6).toString('hex')}`);
  writeFileSync(tmp, body, { mode: 0o600 });
  renameSync(tmp, CADDYFILE);
  return CADDYFILE;
}

/** Remove the Caddyfile entirely (tunnel disabled — Caddy idles inside the
 *  network with no sites). */
export function removeCaddyfile(): void {
  if (existsSync(CADDYFILE)) unlinkSync(CADDYFILE);
}

/** POST the rendered Caddyfile to Caddy's admin :2019/load endpoint. Caddy
 *  expects a JSON config OR adapted-from-Caddyfile-text via the load+adapt
 *  flow at /load with Content-Type: text/caddyfile.
 *
 *  Returns true on success, throws on error. Safe to no-op in dev when Caddy
 *  isn't running (caught by the route handler). */
export async function reloadCaddy(caddyfileText?: string): Promise<void> {
  // /load accepts a Caddyfile when Content-Type: text/caddyfile is set
  // (https://caddyserver.com/docs/api#post-load). Read the freshly-written
  // file from disk by default so we reload exactly what's on disk.
  const body = caddyfileText ?? (existsSync(CADDYFILE) ? (await import('node:fs/promises')).readFile(CADDYFILE, 'utf8') : '');
  const text = typeof body === 'string' ? body : await body;
  const res = await fetch(`${CADDY_ADMIN}/load`, {
    method: 'POST',
    headers: { 'Content-Type': 'text/caddyfile' },
    body: text,
  });
  if (!res.ok) {
    const txt = await res.text().catch(() => '');
    throw new Error(`Caddy reload failed ${res.status}: ${txt.slice(0, 200)}`);
  }
  logger.info('caddy reloaded');
}

export const CADDY_PATHS = { dir: CADDY_DIR, file: CADDYFILE };
